### ISSUE TITLE
Asserts with -g

### ISSUE THREAD

**Issue by tjablin** [HSAFoundation/HSAIL-Tools#29]
Assembling simple hsail files with the -g option yields an assert for me. For example:

$ cat fcos.hsail
//===- fcos.hsail ---------------------------------------------------------===//
//
//                     The HSA Simulator
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//

version 0:96:$full:$small;

//==========================================================
// Function: __Get_fcos
//
// Inputs: arg_val0 - List of values to compute the fcos on
//
// Outputs: arg_val1 - Results
//
//==========================================================

kernel &__Get_fcos(kernarg_u32 %arg_val0, kernarg_u32 %arg_val1)
{
        // Use workitemaid to get the buffer offset
        workitemabsid_u32 $s1, 0;
        shl_u32  $s1, $s1, 2;  // Get offset by Multiplying by 4 because
                               // that is the size of each value in the buffer

        // Compute Address of Input Value and store in $s0
        ld_kernarg_u32  $s0, [%arg_val0];
        add_u32  $s0, $s0, $s1;  // Add offset to Address

        // Compute Address of Output Value and store in $s3
        ld_kernarg_u32  $s3, [%arg_val1];
        add_u32  $s3, $s3, $s1;  // Add offset to Address

        // Execute Trig Opcode
        ld_f32 $s0, [$s0];
        ncos_f32 $s2, $s0;

        // Store Dispatch ID on Kernel Argument
        st_global_u32   $s2, [$s3] ;

        ret;
};

$ ./hsailasm fcos.hsail -o fcos.o -g
hsailasm: libBRIGdwarf/BrigDwarfGenerator.cpp:1332: void BrigDebug::BrigDwarfGenerator_impl::createDwarfElfSections(): Assertion `relType == __R_HSA_DWARF_32' failed.
0  hsailasm        0x0000000000529acb
1  hsailasm        0x0000000000529d48
2  hsailasm        0x00000000005297c4
3  libpthread.so.0 0x00002ba208e68340
4  libc.so.6       0x00002ba2098ccf79 gsignal + 57
5  libc.so.6       0x00002ba2098d0388 abort + 328
6  libc.so.6       0x00002ba2098c5e36
7  libc.so.6       0x00002ba2098c5ee2
8  hsailasm        0x00000000004133c0
9  hsailasm        0x0000000000410afc
10 hsailasm        0x0000000000407adf
11 hsailasm        0x0000000000408065
12 hsailasm        0x0000000000408278
13 libc.so.6       0x00002ba2098b7ec5 __libc_start_main + 245
14 hsailasm        0x0000000000407199

**Comment by tjablin** [comment]
Has there been any progress on this bug? If the -g option doesn't work, then the next version of the HSA simulator will have degraded debugging capabilities.

**Comment by nhaustov** [comment]
Fixed in c3bbfe7d8bc3308eb379dafb7c963d8b6be22aac
