### ISSUE TITLE
libBRIGdwarf does not compile using recent versions of libdwarf

### ISSUE THREAD

**Issue by rollingthunder** [HSAFoundation/HSAIL-Tools#32]
In versions of libdwarf more recent than 20140413, the procedure
`dwarf_producer_init_c`
has been removed.

Consequently, the compilation fails in libBRIGdwarf/BrigDwarfGenerator.cpp in member function ‘void BrigDebug::BrigDwarfGenerator_impl::initializeDwarfProducer()’

**Comment by nhaustov** [comment]
Fixed in c3bbfe7d8bc3308eb379dafb7c963d8b6be22aac.
