### ISSUE TITLE
Ubuntu - HSAILasm link error

### ISSUE THREAD

**Issue by scchan** [HSAFoundation/HSAIL-Tools#40]
On Ubuntu with LLVM 3.4 (default llvm package), the HSAILasm binary will fail to link due to missing symbols such as setupterm, tigetnum, set_curterm...
It will only work if linking in libtinfo

**Comment by nhaustov** [comment]
Siu Chi fixed this one in 560c1b7164291e50a1a33b63d52f5171036f22de
