### ISSUE TITLE
HSAILasm linking failure with older llvm

### ISSUE THREAD

**Issue by jvesely** [HSAFoundation/HSAIL-Tools#41]
/usr/bin/c++     -Wall -std=c++11 -pthread -D __STDC_LIMIT_MACROS -D __STDC_CONSTANT_MACROS  -D __STDC_FORMAT_MACROS -fno-rtti -fvisibility-inlines-hidden   CMakeFiles/HSAILasm.dir/HSAILAsm.cpp.o  -o HSAILasm -rdynamic ../libHSAIL/libhsail.a -lelf -ldwarf -lcurses -ldl -ltinfo /usr/lib64/libdwarf.so 
../libHSAIL/libhsail.a(BrigDwarfGenerator.cpp.o): In function `BrigDebug::BrigDwarfGenerator_impl::initializeElf()':
BrigDwarfGenerator.cpp:(.text+0x26ae): warning: the use of `tempnam' is dangerous, better use `mkstemp'
CMakeFiles/HSAILasm.dir/HSAILAsm.cpp.o: In function `main':
HSAILAsm.cpp:(.text+0x1a): undefined reference to `llvm::sys::PrintStackTraceOnErrorSignal()'
CMakeFiles/HSAILasm.dir/HSAILAsm.cpp.o: In function `llvm::PrettyStackTraceProgram::PrettyStackTraceProgram(int, char const* const*)':
HSAILAsm.cpp:(.text._ZN4llvm23PrettyStackTraceProgramC2EiPKPKc[_ZN4llvm23PrettyStackTraceProgramC5EiPKPKc]+0x1c): undefined reference to `llvm::PrettyStackTraceEntry::PrettyStackTraceEntry()'
HSAILAsm.cpp:(.text._ZN4llvm23PrettyStackTraceProgramC2EiPKPKc[_ZN4llvm23PrettyStackTraceProgramC5EiPKPKc]+0x21): undefined reference to `vtable for llvm::PrettyStackTraceProgram'
HSAILAsm.cpp:(.text._ZN4llvm23PrettyStackTraceProgramC2EiPKPKc[_ZN4llvm23PrettyStackTraceProgramC5EiPKPKc]+0x43): undefined reference to `llvm::EnablePrettyStackTrace()'
HSAILAsm.cpp:(.text._ZN4llvm23PrettyStackTraceProgramC2EiPKPKc[_ZN4llvm23PrettyStackTraceProgramC5EiPKPKc]+0x54): undefined reference to `llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry()'
CMakeFiles/HSAILasm.dir/HSAILAsm.cpp.o: In function `llvm::PrettyStackTraceProgram::~PrettyStackTraceProgram()':
HSAILAsm.cpp:(.text._ZN4llvm23PrettyStackTraceProgramD2Ev[_ZN4llvm23PrettyStackTraceProgramD5Ev]+0xd): undefined reference to `vtable for llvm::PrettyStackTraceProgram'
HSAILAsm.cpp:(.text._ZN4llvm23PrettyStackTraceProgramD2Ev[_ZN4llvm23PrettyStackTraceProgramD5Ev]+0x20): undefined reference to `llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry()'
collect2: error: ld returned 1 exit status

**Comment by jvesely** [comment]
This happens because cmake finds LLVMSUpport library in different location than provided by  llvm-config --libdir

**Comment by jvesely** [comment]
Subject: [PATCH] cmake,llvm: Fix llvm library lookup

support symbols can be in:
libLLVMSupport
libLLVM-X.Y.so
libLLVM-X.Y.Z.so
libLLVM.so.X.Y{.Z}

search only the provided llvm libdir to avoid cross linking to other llvm instalations

Signed-off-by: Jan Vesely <jan.vesely@amd.com>
---
 libHSAIL/cmake_modules/FindLLVM.cmake | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/libHSAIL/cmake_modules/FindLLVM.cmake b/libHSAIL/cmake_modules/FindLLVM.cmake
index 87a3577..19e3dc7 100644
--- a/libHSAIL/cmake_modules/FindLLVM.cmake
+++ b/libHSAIL/cmake_modules/FindLLVM.cmake
@@ -4,7 +4,11 @@ cmake_minimum_required(VERSION 2.8.8)
 find_program(LLVM_CONFIG_EXE NAMES "llvm-config")
 execute_process(COMMAND ${LLVM_CONFIG_EXE} --libdir OUTPUT_VARIABLE LLVM_LIB_DIR
          OUTPUT_STRIP_TRAILING_WHITESPACE )
+execute_process(COMMAND ${LLVM_CONFIG_EXE} --version OUTPUT_VARIABLE LLVM_VERSION
+         OUTPUT_STRIP_TRAILING_WHITESPACE )
 
-message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION} dir ${LLVM_DIR}")
+message(STATUS "Found LLVM ${LLVM_VERSION} dir ${LLVM_LIB_DIR}")
 
-find_library(LLVM_SUPPORT_LIB LLVMSupport PATHS ${LLVM_LIB_DIR})
+find_library(LLVM_SUPPORT_LIB LLVMSupport PATHS ${LLVM_LIB_DIR} NO_DEFAULT_PATH)
+find_library(LLVM_SUPPORT_LIB LLVM-${LLVM_VERSION} PATHS ${LLVM_LIB_DIR} NO_DEFAULT_PATH)
+find_library(LLVM_SUPPORT_LIB LLVM PATHS ${LLVM_LIB_DIR} NO_DEFAULT_PATH)
-- 
2.4.3

**Comment by arsenm** [comment]
Can you submit your patch as a pull request? I got a mail with a patch attached to this thread but it seems to have disappeared

**Comment by jvesely** [comment]
I posted the patch as comment, but the forum messed it up so I deleted the post and sent the patch to SiuChi instead.
Attaching it to comment does not work either ("Something went really wrong, and we can'
t process that file").
Now there's a pull request too.
GH really needs "create pull request from patch(es)" feature

**Comment by nhaustov** [comment]
Fixed in c56236b.
