### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [HSAFoundation/HSAIL-Tools#44]
I would like to point out that identifiers like "[`__BRIG_DWARF_GENERATOR_H__`](https://github.com/HSAFoundation/HSAIL-Tools/blob/0ebb93bbf56b48dc4be2d179dcf9b2384f76b70f/libHSAIL/BrigDwarfGenerator.h#L41)" and "[`__R_HSA_DWARF_TO_BRIG_DIRECTIVES64`](https://github.com/HSAFoundation/HSAIL-Tools/blob/0ebb93bbf56b48dc4be2d179dcf9b2384f76b70f/libHSAIL/hsa_dwarf.h#L55)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by kasaurov** [comment]
Fixed by https://github.com/HSAFoundation/HSAIL-Tools/commit/f9e5dc21d67fd154dfe5b90e10c6ac744a02157d

**Comment by elfring** [comment]
There are [a few update candidates left over](https://github.com/HSAFoundation/HSAIL-Tools/commit/f9e5dc21d67fd154dfe5b90e10c6ac744a02157d#diff-cf1f374fcb3401efb1a379136e181b7aR41 "Update candidate").
Would you like to [delete any more underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") from affected identifiers?
