### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [HSAFoundation/HSAIL-Tools#45]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/HSAFoundation/HSAIL-Tools/blob/0ebb93bbf56b48dc4be2d179dcf9b2384f76b70f/HSAILAsm/HSAILAsm.cpp#L71 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by nhaustov** [comment]
The exceptions do not escape HSAILTool class, so there is no need to catch them in main method.

**Comment by elfring** [comment]
Can the actions before the call of the member function "execute" from the variable "tool" trigger any C++ exceptions?
