### ISSUE TITLE
Error: Invalid libHSAIL option when using -g option

### ISSUE THREAD

**Issue by PXAHyLee** [HSAFoundation/HSAIL-Tools#47]
Dear developer,

In [the system requirements of HSA-Debugger](https://github.com/HSAFoundation/HSA-Debugger-AMD#system-requirements), it states that the HSAIL applications must be built with HSAIL-Tools.

Thus, I built the HSAILasm successfully with the option BUILD_LIBBRIGDWARF and BUILD_HSAILASM.

However, when I execute `HSAILasm -assemble -g  matrixMul_kernel.hsail`, it states that
`Error: Invalid libHSAIL option: matrixMul_kernel.hsail`. The `-help` option states that `Usage: HSAILAsm [-assemble|-disassemble|-decode|-version|-help] [options] [input file]`.

Is there anything that I missed so far?

Thanks.

**Comment by nhaustov** [comment]
Should be fixed by 7106c0f
