### ISSUE TITLE
HSAILasm disassembles an illegal BRIG with an illegal store argument list without complaining

### ISSUE THREAD

**Issue by pjaaskel** [HSAFoundation/HSAIL-Tools#48]
There's an illegal instruction in a BRIG:

> st_align(4)_u8 9, 0, 0, 0, [$d0+8];

st takes only two arguments, this has somehow pushed in 5. HSAILasm can disassemble the BRIG, but cannot assemble it again:

$ HSAILasm -disassemble phsa-temp/program-0.brig 
$ HSAILasm phsa-temp/program-0.hsail

>       st_align(4)_u8  9, 0, 0, 0, [$d0+8];
>                          ^
input(10,20): Invalid operand 1, expected: an address

See: https://github.com/HSAFoundation/gccbrig/issues/4

**Comment by pjaaskel** [comment]
The culprit:
[z.brig.gz](https://github.com/HSAFoundation/HSAIL-Tools/files/187931/z.brig.gz)

**Comment by dpreobrazhensky** [comment]
A fix for this issue has just been pushed on GitHub

**Comment by pjaaskel** [comment]
Verified. Thanks.
